#!/bin/sh
if [[ $(uname) == "MINGW"* ]]; then
    echo "On Windows"
    # exec pwsh -NoProfile -File .git/hooks/pre-commit.ps1
else
    echo "On *nix"
fi

# From: https://github.com/Drafteame/ejson-hooks/blob/main/run-encrypt.sh

# Get the list of modified and added files
FILES=$(git diff-index --cached --name-status HEAD | awk '$1 == "M" || $1 == "A" { print $2 }')
EXIT_CODE=0
VOLUME_ROOT=$(pwd)

# Loop through the files and encrypt if they match the ejson extension
for FILE in $FILES; do
  if [ "${FILE##*.}" = "ejson" ]; then
    # Encrypt the ejson file
    # TODO: try to work around the fact that the volume name '/data' is transformed to '\Program Files\Git\data' ?!?
    #docker run -v "${VOLUME_ROOT}"":/var/abc" --rm -t debian ls
    #ejson_output=$(docker run -v "${VOLUME_ROOT}:/data" --rm -t -w "/data" shinkou/ejson encrypt ${FILE} 2>&1)

    # check if ejson exit code is different from 0
    if [ $? -ne 0 ]; then
        echo "Error encoding file $FILE: $ejson_output"
        EXIT_CODE=1
    else
      # Stage the decrypted file
      git add $FILE
    fi
  fi
done

# Continue with the commit
exit $EXIT_CODE
