# Services necessary for local dev

services:
  postgres_svc:
    container_name: postgres_ctnr
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
        - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
